# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: gamemanagament
service: apollo-lambda
provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    cors: true
functions:
  graphql:
    handler: src/index.graphqlHandler
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
plugins:
  - serverless-dotenv-plugin
package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
